name: docker publish
on:
  workflow_run:
    workflows: ["bump version"]
    branches: [master]
    types: 
      - completed

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          GHCR_IMAGE=ghcr.io/${{ github.repository_owner }}/decompose
          VERSION=${GITHUB_REF#refs/tags/v}
          TAGS="${TAGS},${GHCR_IMAGE}:${VERSION},${GHCR_IMAGE}:latest"
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=ghcr_image::${GHCR_IMAGE}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to Github Container Registry
        uses: docker/login-action@v1.8.0
        with:
          registry: docker.pkg.github.com
          username: decayops
          password: ${{ secrets.DECAYOPS }}

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: docker.pkg.github.com/decaydev/decompose/decaydev-decompose
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: org.opencontainers.image.version=${{ steps.prep.outputs.version }}
          
