name: tag version
on:
  workflow_run:
    workflows: ["python install and lint"]
    branches: [master]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: bump
        uses: zwaldowski/match-label-action@v1
        with:
          allowed: major,minor,patch
      - uses: zwaldowski/semver-release-action@v1
        with:
          bump: ${{ steps.bump.outputs.match }}
          github_token: ${{ secrets.GITHUB_TOKEN }}  
