name: tag version
on:
  workflow_run:
    workflows: ["python install and lint"]
    branches: [master]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bump Version
      id: tag
      uses: mathieudutour/github-tag-action@v4.5
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: release
      uses: ncipollo/release-action@v1
      if: github.ref == 'refs/heads/master'
      with:
        name: "Release ${{ steps.tag.outputs.new_tag }}"
        body: "latest release"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.tag.outputs.new_tag }}
